// Liana's ASBOG FG study bank.
// PROVENANCE: every item is tagged. source:"original" = written from scratch to the
// ASBOG FG content domains (safe for a future product). productSafe:true = OK to ship.
// If publisher/copyrighted questions (Mometrix, etc.) are ever added, tag them
// source:"<publisher>" and productSafe:false so the product build filters them out.
// Schema: {id, domain, topic, difficulty, q, choices:[4], answer:<idx>, explain, source, productSafe}
window.GEO_DOMAINS = [
  { key:"general",   name:"General & Field Geology",
    blurb:"Maps, strike/dip, dating principles, field methods, basic Earth science.",
    resources:[
      ["Physical Geology (Earle) — Ch.1 & Geologic Time","https://opentextbc.ca/physicalgeology2ed/"],
      ["USGS — Topographic maps","https://www.usgs.gov/programs/national-geospatial-program/topographic-maps"]]},
  { key:"mineralogy", name:"Mineralogy, Petrology & Geochemistry",
    blurb:"Minerals, igneous/metamorphic rocks, Bowen's series, isotopes.",
    resources:[
      ["Physical Geology (Earle) — Minerals & Igneous Rocks","https://opentextbc.ca/physicalgeology2ed/"],
      ["USGS — Minerals","https://www.usgs.gov/programs/mineral-resources-program"]]},
  { key:"sedimentary", name:"Sedimentology, Stratigraphy & Paleontology",
    blurb:"Clastic/chemical sediments, depositional environments, correlation, fossils.",
    resources:[["Physical Geology (Earle) — Sedimentary Rocks","https://opentextbc.ca/physicalgeology2ed/"]]},
  { key:"geomorph",  name:"Geomorphology & Surficial Processes",
    blurb:"Weathering, soils, rivers, glaciers, coasts, mass wasting, Quaternary.",
    resources:[["Physical Geology (Earle) — Streams/Glaciers/Mass Wasting","https://opentextbc.ca/physicalgeology2ed/"]]},
  { key:"structure", name:"Structure, Tectonics & Seismology",
    blurb:"Folds, faults, plate boundaries, earthquakes, seismic waves.",
    resources:[
      ["Physical Geology (Earle) — Plate Tectonics & Structures","https://opentextbc.ca/physicalgeology2ed/"],
      ["USGS Earthquake Hazards","https://earthquake.usgs.gov/"]]},
  { key:"hydro",     name:"Hydrogeology",
    blurb:"Porosity/permeability, Darcy's law, aquifers, wells, contaminant transport.",
    resources:[
      ["Physical Geology (Earle) — Groundwater","https://opentextbc.ca/physicalgeology2ed/"],
      ["USGS Water Resources","https://www.usgs.gov/mission-areas/water-resources"]]},
  { key:"engineering", name:"Engineering Geology",
    blurb:"Soil/rock mechanics, slope stability, foundations, liquefaction, geohazards.",
    resources:[["USGS Landslide Hazards","https://www.usgs.gov/programs/landslide-hazards"]]},
  { key:"economic",  name:"Economic Geology & Energy",
    blurb:"Ore deposits, petroleum systems, coal, resources vs reserves.",
    resources:[["USGS Energy Resources","https://www.usgs.gov/programs/energy-resources-program"]]},
];

window.GEO_QUESTIONS = [
  // ===== GENERAL & FIELD GEOLOGY =====
  {id:1,domain:"general",topic:"Field methods",difficulty:"medium",q:"In a geologic 'strike and dip' measurement, the DIP is:",choices:["The compass bearing of a horizontal line on the bed","The angle the bed makes below horizontal, measured perpendicular to strike","The thickness of the bed","The depth to the bed"],answer:1,explain:"Strike is the bearing of a horizontal line on the inclined plane; dip is the maximum angle of inclination below horizontal, measured at 90° to strike.",source:"original",productSafe:true},
  {id:2,domain:"general",topic:"Topographic maps",difficulty:"easy",q:"On a topographic map, contour lines spaced very close together indicate:",choices:["A gentle slope","A steep slope","Flat ground","A depression"],answer:1,explain:"Closely spaced contours = rapid elevation change = steep slope. Widely spaced = gentle.",source:"original",productSafe:true},
  {id:3,domain:"general",topic:"Topographic maps",difficulty:"medium",q:"Where contour lines cross a stream valley, the 'V' of the contours points:",choices:["Downstream","Upstream","Always north","Toward the nearest peak"],answer:1,explain:"Contours bend upstream (uphill) as they cross a valley, so the V points upstream.",source:"original",productSafe:true},
  {id:4,domain:"general",topic:"Relative dating",difficulty:"easy",q:"The principle of cross-cutting relationships states that:",choices:["A fault or intrusion is younger than the rocks it cuts","The bottom layer is always igneous","Fossils get younger downward","Folds form before deposition"],answer:0,explain:"Any feature that cuts across another (fault, dike, intrusion) must be younger than what it disrupts.",source:"original",productSafe:true},
  {id:5,domain:"general",topic:"Relative dating",difficulty:"easy",q:"Steno's principle of original horizontality states that sedimentary layers are originally deposited:",choices:["Vertically","At random angles","Horizontally (or nearly so)","Only on slopes"],answer:2,explain:"Sediments settle under gravity into roughly horizontal layers; tilted beds were deformed after deposition.",source:"original",productSafe:true},
  {id:6,domain:"general",topic:"Map scale",difficulty:"medium",q:"A map at a scale of 1:24,000 means one inch on the map equals about:",choices:["24,000 inches (≈2,000 ft)","24,000 miles","240 ft","24 ft"],answer:0,explain:"1:24,000 means 1 unit on the map = 24,000 units on the ground; 24,000 in ≈ 2,000 ft. This is the standard USGS quadrangle scale.",source:"original",productSafe:true},
  {id:7,domain:"general",topic:"Dating",difficulty:"medium",q:"Relative dating differs from absolute (numerical) dating in that relative dating:",choices:["Gives an age in years","Establishes age order/sequence without exact years","Requires radioactive isotopes","Only works on fossils"],answer:1,explain:"Relative dating orders events (older/younger) using principles like superposition; absolute dating assigns numeric ages (e.g., via isotopes).",source:"original",productSafe:true},
  {id:8,domain:"general",topic:"Geologic time",difficulty:"easy",q:"Non-avian dinosaurs dominated land during which era?",choices:["Paleozoic","Mesozoic","Cenozoic","Precambrian"],answer:1,explain:"The Mesozoic (Triassic–Jurassic–Cretaceous) ended ~66 Ma at the K-Pg extinction; mammals radiated in the following Cenozoic.",source:"original",productSafe:true},
  {id:9,domain:"general",topic:"Earth structure",difficulty:"medium",q:"Which Earth layer is interpreted as LIQUID based on the S-wave shadow zone?",choices:["Inner core","Outer core","Lower mantle","Crust"],answer:1,explain:"S-waves cannot pass through liquid, so they are blocked by the liquid outer core, producing the S-wave shadow zone. The inner core is solid.",source:"original",productSafe:true},
  {id:10,domain:"general",topic:"Field safety/ethics",difficulty:"easy",q:"A licensed professional geologist's stamp/seal on a report primarily certifies that:",choices:["The work meets professional standards and the geologist takes responsibility for it","The client approved the budget","The data are guaranteed error-free forever","The report is copyrighted"],answer:0,explain:"The seal signifies the work was done by/under a licensed PG to accepted professional standards, with accountability for protecting public welfare.",source:"original",productSafe:true},

  // ===== MINERALOGY, PETROLOGY & GEOCHEMISTRY =====
  {id:11,domain:"mineralogy",topic:"Mineral ID",difficulty:"easy",q:"On the Mohs hardness scale, which mineral defines a hardness of 7?",choices:["Talc","Calcite","Quartz","Topaz"],answer:2,explain:"Quartz = 7 (talc 1, calcite 3, topaz 8). Quartz scratches glass and steel.",source:"original",productSafe:true},
  {id:12,domain:"mineralogy",topic:"Mineral ID",difficulty:"easy",q:"Which simple field test best distinguishes calcite from quartz?",choices:["Calcite fizzes (effervesces) with dilute HCl","Calcite is magnetic","Calcite is heavier","Quartz dissolves in water"],answer:0,explain:"Calcite (a carbonate) reacts with dilute HCl, releasing CO2 bubbles; quartz does not react.",source:"original",productSafe:true},
  {id:13,domain:"mineralogy",topic:"Crystal chemistry",difficulty:"hard",q:"Quartz (SiO2) is classified as which silicate structure?",choices:["Isolated tetrahedra (nesosilicate)","Single chain (inosilicate)","Sheet (phyllosilicate)","Framework (tectosilicate)"],answer:3,explain:"In quartz every oxygen is shared between two tetrahedra (3-D framework), giving the 1:2 Si:O ratio. Olivine = neso-, pyroxene = single-chain, mica = sheet.",source:"original",productSafe:true},
  {id:14,domain:"mineralogy",topic:"Igneous",difficulty:"medium",q:"According to Bowen's reaction series, which mineral crystallizes at the HIGHEST temperature?",choices:["Quartz","Muscovite","Olivine","K-feldspar"],answer:2,explain:"Olivine is at the high-temperature top of the discontinuous series; quartz, muscovite, and K-feldspar form last (lowest T).",source:"original",productSafe:true},
  {id:15,domain:"mineralogy",topic:"Igneous",difficulty:"easy",q:"The fine-grained extrusive equivalent of granite is:",choices:["Basalt","Gabbro","Rhyolite","Andesite"],answer:2,explain:"Rhyolite shares granite's felsic composition but cools rapidly at the surface. Gabbro = mafic intrusive, basalt = mafic extrusive.",source:"original",productSafe:true},
  {id:16,domain:"mineralogy",topic:"Igneous",difficulty:"easy",q:"A mafic igneous rock is:",choices:["High-silica, light, quartz-rich","Low-silica, dark, Fe-Mg-rich","Always glassy","Carbonate-rich"],answer:1,explain:"Mafic = low silica, dark, rich in iron/magnesium minerals (basalt/gabbro). Felsic is the high-silica, light counterpart.",source:"original",productSafe:true},
  {id:17,domain:"mineralogy",topic:"Metamorphic",difficulty:"medium",q:"Which lists foliated metamorphic rocks in order of INCREASING grade?",choices:["Gneiss → schist → phyllite → slate","Slate → phyllite → schist → gneiss","Schist → slate → gneiss → phyllite","Phyllite → slate → schist → gneiss"],answer:1,explain:"Increasing T/P: slate → phyllite → schist → gneiss, with coarsening grain size and mineral banding.",source:"original",productSafe:true},
  {id:18,domain:"mineralogy",topic:"Metamorphic",difficulty:"easy",q:"Marble forms by metamorphism of:",choices:["Sandstone","Limestone/dolostone","Shale","Basalt"],answer:1,explain:"Marble = metamorphosed carbonate. Quartzite ← sandstone, slate/schist ← shale.",source:"original",productSafe:true},
  {id:19,domain:"mineralogy",topic:"Geochemistry",difficulty:"medium",q:"Radiocarbon (¹⁴C) dating is appropriate for organic materials up to roughly:",choices:["~50,000 years","~500 million years","~4.6 billion years","~100 years only"],answer:0,explain:"With a ~5,730-yr half-life, ¹⁴C is useful to ~50 ka. Older materials need U-Pb, K-Ar, etc.",source:"original",productSafe:true},

  // ===== SEDIMENTOLOGY, STRATIGRAPHY & PALEONTOLOGY =====
  {id:20,domain:"sedimentary",topic:"Clastics",difficulty:"easy",q:"Which clastic sediment has the LARGEST grain size?",choices:["Clay","Silt","Sand","Gravel"],answer:3,explain:"Wentworth scale: gravel (>2 mm) > sand > silt > clay (finest).",source:"original",productSafe:true},
  {id:21,domain:"sedimentary",topic:"Texture",difficulty:"medium",q:"Well-rounded, well-sorted sand grains indicate:",choices:["Very short transport","Extensive transport/reworking","Glacial till","Chemical precipitation"],answer:1,explain:"Rounding and sorting increase with transport distance and energy; glacial till is angular and poorly sorted.",source:"original",productSafe:true},
  {id:22,domain:"sedimentary",topic:"Structures",difficulty:"medium",q:"Cross-bedding is most useful for interpreting:",choices:["Paleocurrent direction","Absolute age","Metamorphic grade","Magnetic reversals"],answer:0,explain:"Cross-bed foresets dip down-current, recording flow direction and environment (dunes/ripples).",source:"original",productSafe:true},
  {id:23,domain:"sedimentary",topic:"Way-up indicators",difficulty:"hard",q:"In a turbidite, graded bedding (coarse at base fining upward) is used to determine:",choices:["The stratigraphic 'way up' (which side was originally up)","The exact age","The water depth in meters","The magnetic field"],answer:0,explain:"Normal grading fines upward, so the coarse end marks the original bottom, a key way-up indicator in deformed strata.",source:"original",productSafe:true},
  {id:24,domain:"sedimentary",topic:"Stratigraphy",difficulty:"easy",q:"The principle of superposition states that in an undeformed sequence:",choices:["Younger layers lie below older","Older at bottom, younger on top","All layers are the same age","Layers form vertically"],answer:1,explain:"Each undisturbed layer is younger than the one beneath it.",source:"original",productSafe:true},
  {id:25,domain:"sedimentary",topic:"Unconformities",difficulty:"hard",q:"An angular unconformity is:",choices:["Two parallel conformable beds","Tilted/folded older rocks eroded and overlain by flat-lying younger strata","An igneous sill","A fault contact"],answer:1,explain:"Older beds were tilted and eroded, then younger flat beds deposited on top (angular discordance). Disconformity = parallel; nonconformity = strata on eroded crystalline basement.",source:"original",productSafe:true},
  {id:26,domain:"sedimentary",topic:"Paleontology",difficulty:"easy",q:"A good index (guide) fossil is:",choices:["Geographically restricted and long-lived","Widespread but short-lived","Only in igneous rocks","Still alive today"],answer:1,explain:"Widespread (for correlation) and short time range (for precision). Both are required.",source:"original",productSafe:true},
  {id:27,domain:"sedimentary",topic:"Facies",difficulty:"hard",q:"Walther's Law states that facies occurring in a conformable vertical succession also:",choices:["Occurred side-by-side laterally in adjacent environments","Are all the same age","Indicate a mass extinction","Formed by metamorphism"],answer:0,explain:"Vertically stacked conformable facies represent laterally adjacent depositional environments that migrated over time.",source:"original",productSafe:true},

  // ===== GEOMORPHOLOGY & SURFICIAL PROCESSES =====
  {id:28,domain:"geomorph",topic:"Glacial",difficulty:"easy",q:"A broad U-shaped valley is most diagnostic of erosion by:",choices:["A river","A glacier","Wind","Groundwater"],answer:1,explain:"Glaciers carve flat-bottomed, steep-walled U-shaped valleys; rivers cut V-shaped valleys.",source:"original",productSafe:true},
  {id:29,domain:"geomorph",topic:"Glacial",difficulty:"medium",q:"An unsorted, unstratified glacial sediment deposited directly by ice is called:",choices:["Till","Loess","Alluvium","Varve"],answer:0,explain:"Till is deposited directly by ice (poorly sorted). Outwash is sorted meltwater sediment; loess is wind-blown silt.",source:"original",productSafe:true},
  {id:30,domain:"geomorph",topic:"Fluvial",difficulty:"medium",q:"Braided streams (vs meandering) typically form where there is:",choices:["Low gradient and fine suspended load","High, variable sediment load and discharge","No sediment supply","Tidal influence only"],answer:1,explain:"Braided channels form with abundant coarse bedload and variable discharge; meandering channels favor lower gradients and suspended load.",source:"original",productSafe:true},
  {id:31,domain:"geomorph",topic:"Eolian",difficulty:"easy",q:"Loess is a deposit of:",choices:["Wind-blown silt","River gravel","Volcanic ash flows","Beach sand"],answer:0,explain:"Loess is wind-transported silt, often blanketing regions downwind of glacial outwash.",source:"original",productSafe:true},
  {id:32,domain:"geomorph",topic:"Karst",difficulty:"medium",q:"Karst topography (sinkholes, caves) develops mainly by:",choices:["Dissolution of soluble rock like limestone","Glacial plucking","Wind abrasion","Lava flows"],answer:0,explain:"Slightly acidic groundwater dissolves carbonate (and evaporite) rock, creating caves and sinkholes.",source:"original",productSafe:true},
  {id:33,domain:"geomorph",topic:"Soils",difficulty:"medium",q:"In a typical soil profile, the organic-rich surface layer is the:",choices:["O horizon","B horizon","C horizon","R horizon"],answer:0,explain:"O = organic surface; A = topsoil; B = zone of accumulation; C = weathered parent material; R = bedrock.",source:"original",productSafe:true},
  {id:34,domain:"geomorph",topic:"Mass wasting",difficulty:"medium",q:"The slow, gradual downslope movement of soil under gravity is called:",choices:["Rockfall","Creep","Liquefaction","Saltation"],answer:1,explain:"Creep is imperceptibly slow downslope soil movement (tilted poles/fences are evidence). Rockfall is rapid free-fall of rock.",source:"original",productSafe:true},

  // ===== STRUCTURE, TECTONICS & SEISMOLOGY =====
  {id:35,domain:"structure",topic:"Faults",difficulty:"medium",q:"In a normal fault, the hanging wall moves ___ under ___ stress.",choices:["up; compression","down; extension","laterally; shear","none; lithostatic"],answer:1,explain:"Normal faults drop the hanging wall under extension; reverse/thrust faults raise it under compression.",source:"original",productSafe:true},
  {id:36,domain:"structure",topic:"Folds",difficulty:"medium",q:"In an eroded anticline, the oldest rocks are exposed:",choices:["In the core (center)","On the outer limbs","At the surface edges","Randomly"],answer:0,explain:"Anticlines arch up, exposing oldest beds in the core; synclines have youngest rocks in the core.",source:"original",productSafe:true},
  {id:37,domain:"structure",topic:"Plate boundaries",difficulty:"easy",q:"Mid-ocean ridges and seafloor spreading occur at which boundary?",choices:["Convergent","Divergent","Transform","Passive margin"],answer:1,explain:"Divergent boundaries create new oceanic crust at ridges.",source:"original",productSafe:true},
  {id:38,domain:"structure",topic:"Plate boundaries",difficulty:"medium",q:"Deep trenches, inclined deep-earthquake zones, and volcanic arcs characterize:",choices:["Divergent boundaries","Convergent (subduction) boundaries","Transform boundaries","Hotspots"],answer:1,explain:"A subducting slab creates the trench, the Wadati-Benioff seismic zone, and arc volcanism.",source:"original",productSafe:true},
  {id:39,domain:"structure",topic:"Seismology",difficulty:"hard",q:"Which statement about seismic body waves is CORRECT?",choices:["S-waves are faster than P-waves","P-waves cannot pass through liquids","S-waves cannot travel through the liquid outer core","Both travel only through solids"],answer:2,explain:"P-waves (fastest, compressional) pass through solids and liquids; S-waves (shear) cannot pass through liquids.",source:"original",productSafe:true},
  {id:40,domain:"structure",topic:"Seismology",difficulty:"medium",q:"To locate an earthquake's epicenter, you minimally need data from:",choices:["One seismograph","Two seismographs","Three or more seismographs (triangulation)","No seismographs"],answer:2,explain:"S–P arrival times give distance to each station; three+ distance circles triangulate the epicenter.",source:"original",productSafe:true},

  // ===== HYDROGEOLOGY =====
  {id:41,domain:"hydro",topic:"Properties",difficulty:"medium",q:"Permeability differs from porosity in that permeability measures:",choices:["Total void fraction","The ability to transmit fluid","Mineral hardness","Grain diameter"],answer:1,explain:"Porosity = void fraction; permeability = how well voids interconnect to transmit fluid. Clay is porous but nearly impermeable.",source:"original",productSafe:true},
  {id:42,domain:"hydro",topic:"Darcy's law",difficulty:"hard",q:"In Darcy's law (Q = K·i·A), the term 'i' represents the:",choices:["Hydraulic gradient (head change per distance)","Porosity","Pumping rate","Pipe diameter"],answer:0,explain:"Q = K i A: K = hydraulic conductivity, i = hydraulic gradient (dh/dl), A = cross-sectional area. Flow increases with gradient and conductivity.",source:"original",productSafe:true},
  {id:43,domain:"hydro",topic:"Aquifers",difficulty:"medium",q:"A low-permeability layer that retards groundwater flow is an:",choices:["Aquifer","Aquitard/aquiclude","Artesian well","Aquihole"],answer:1,explain:"An aquitard (or aquiclude) restricts flow; an aquifer readily stores and transmits water.",source:"original",productSafe:true},
  {id:44,domain:"hydro",topic:"Aquifers",difficulty:"medium",q:"Water in a confined aquifer under enough pressure to rise above the aquifer top in a well is:",choices:["Perched water","Artesian (confined) conditions","An unconfined aquifer","A vadose zone"],answer:1,explain:"Confined aquifers between aquitards can be pressurized; the potentiometric surface lies above the aquifer top (artesian).",source:"original",productSafe:true},
  {id:45,domain:"hydro",topic:"Wells",difficulty:"medium",q:"Pumping a well lowers the water table around it into a feature called the:",choices:["Cone of depression","Capillary fringe","Recharge mound","Perched lens"],answer:0,explain:"Drawdown creates a cone of depression centered on the pumping well; overlapping cones cause well interference.",source:"original",productSafe:true},
  {id:46,domain:"hydro",topic:"Water table",difficulty:"easy",q:"The water table is best defined as:",choices:["The top of the zone of saturation","The bottom of all groundwater","The ground surface","An impermeable layer"],answer:0,explain:"It is the surface separating the unsaturated (vadose) zone above from the saturated zone below.",source:"original",productSafe:true},
  {id:47,domain:"hydro",topic:"Contaminant transport",difficulty:"hard",q:"A dissolved contaminant plume in groundwater generally migrates:",choices:["Upward against gravity","Down the hydraulic gradient (toward lower head)","Only sideways at random","It never moves"],answer:1,explain:"Advection carries dissolved contaminants in the direction of groundwater flow, i.e., down the hydraulic gradient, with dispersion spreading the plume.",source:"original",productSafe:true},
  {id:48,domain:"hydro",topic:"Storage",difficulty:"hard",q:"Specific yield is the portion of water that a saturated material will:",choices:["Release by gravity drainage","Retain by surface tension","Convert to vapor","Freeze"],answer:0,explain:"Specific yield = drainable water; specific retention = water held against gravity. Porosity ≈ specific yield + specific retention.",source:"original",productSafe:true},
  {id:49,domain:"hydro",topic:"Properties",difficulty:"medium",q:"Which earth material typically has HIGH porosity but LOW permeability?",choices:["Clean gravel","Fractured basalt","Clay","Well-sorted sand"],answer:2,explain:"Clay has lots of tiny pores (high porosity) but the pores are poorly connected and hold water tightly, giving very low permeability.",source:"original",productSafe:true},
  {id:50,domain:"hydro",topic:"Quantities",difficulty:"hard",q:"Transmissivity equals hydraulic conductivity multiplied by:",choices:["The saturated aquifer thickness","The porosity","The pumping time","The well radius"],answer:0,explain:"T = K·b, where b is the saturated thickness; it describes how much water an aquifer's full thickness can transmit.",source:"original",productSafe:true},

  // ===== ENGINEERING GEOLOGY =====
  {id:51,domain:"engineering",topic:"Soil mechanics",difficulty:"hard",q:"Terzaghi's effective stress (σ′) equals total stress (σ) minus:",choices:["Pore-water pressure (u)","Cohesion","The friction angle","Overburden"],answer:0,explain:"σ′ = σ − u. Rising pore pressure lowers effective stress and shear strength, a key idea in slope and foundation failure.",source:"original",productSafe:true},
  {id:52,domain:"engineering",topic:"Geohazards",difficulty:"medium",q:"Liquefaction during an earthquake is most likely in:",choices:["Dry bedrock","Loose, saturated sand/silt","Dense gravel above the water table","Solid granite"],answer:1,explain:"Shaking raises pore pressure in loose, saturated granular soils until they lose strength and behave like a fluid.",source:"original",productSafe:true},
  {id:53,domain:"engineering",topic:"Soil index",difficulty:"hard",q:"Atterberg limits (liquid limit, plastic limit) are used to characterize:",choices:["The consistency/plasticity behavior of fine-grained soils","Rock hardness","Permeability of gravel","Seismic velocity"],answer:0,explain:"They mark water contents where a fine soil changes behavior; plasticity index = LL − PL, used in soil classification.",source:"original",productSafe:true},
  {id:54,domain:"engineering",topic:"Expansive soils",difficulty:"medium",q:"Which clay mineral causes the most damaging shrink-swell (expansive) behavior?",choices:["Kaolinite","Smectite (montmorillonite)","Quartz","Gypsum"],answer:1,explain:"Smectite/montmorillonite absorbs water between layers and swells, cracking foundations and pavements.",source:"original",productSafe:true},
  {id:55,domain:"engineering",topic:"Slope stability",difficulty:"medium",q:"A slope's factor of safety is the ratio of:",choices:["Resisting forces to driving forces","Cost to benefit","Rainfall to runoff","Porosity to permeability"],answer:0,explain:"FS = resisting/driving forces; FS < 1 means failure. Adding water (driving forces up, strength down) lowers FS.",source:"original",productSafe:true},
  {id:56,domain:"engineering",topic:"Rock mass",difficulty:"hard",q:"Rock Quality Designation (RQD) is computed from drill core as:",choices:["The % of core in intact pieces ≥ 10 cm long","The core diameter","The drilling speed","The number of minerals present"],answer:0,explain:"RQD = (sum of core pieces ≥10 cm / total core run) × 100; higher RQD = more competent, less fractured rock.",source:"original",productSafe:true},
  {id:57,domain:"engineering",topic:"Foundations",difficulty:"medium",q:"The maximum slope angle a loose granular pile can maintain is its:",choices:["Angle of repose","Dip angle","Liquid limit","Hydraulic gradient"],answer:0,explain:"The angle of repose is the steepest stable angle for loose, dry granular material.",source:"original",productSafe:true},
  {id:58,domain:"engineering",topic:"Mass wasting",difficulty:"medium",q:"A slump is a mass movement that:",choices:["Falls freely through air","Rotates downward along a curved (concave) failure surface","Flows as a saturated slurry","Creeps over centuries"],answer:1,explain:"Slumps move as coherent blocks rotating along a curved (spoon-shaped) slip surface, often leaving a back-tilted scarp.",source:"original",productSafe:true},

  // ===== ECONOMIC GEOLOGY & ENERGY =====
  {id:59,domain:"economic",topic:"Petroleum",difficulty:"hard",q:"A complete petroleum system minimally requires a source rock, a migration path, a trap, and:",choices:["A porous/permeable reservoir plus an impermeable seal","A coal seam","A fault only","A volcanic vent"],answer:0,explain:"Hydrocarbons form in an organic source rock, migrate into a porous-permeable reservoir, and are held by a seal/cap rock within a structural or stratigraphic trap.",source:"original",productSafe:true},
  {id:60,domain:"economic",topic:"Coal",difficulty:"medium",q:"Which lists coal in order of INCREASING rank (carbon content/maturity)?",choices:["Anthracite → bituminous → lignite → peat","Peat → lignite → bituminous → anthracite","Lignite → peat → anthracite → bituminous","Bituminous → peat → lignite → anthracite"],answer:1,explain:"Increasing burial/heat: peat → lignite → sub-bituminous → bituminous → anthracite (highest rank, most carbon).",source:"original",productSafe:true},
  {id:61,domain:"economic",topic:"Ore deposits",difficulty:"hard",q:"Porphyry copper deposits are:",choices:["High-grade veins in limestone","Large, low-grade disseminated deposits linked to intermediate-felsic intrusions","Placer concentrations in rivers","Evaporite beds"],answer:1,explain:"Porphyry deposits are large-tonnage, low-grade disseminated sulfides associated with shallow intrusions; they supply most of the world's copper.",source:"original",productSafe:true},
  {id:62,domain:"economic",topic:"Ore deposits",difficulty:"medium",q:"Placer gold deposits form by:",choices:["Mechanical concentration of dense grains in flowing water","Volcanic eruption","Metamorphism of shale","Evaporation of seawater"],answer:0,explain:"Heavy, resistant minerals (gold, magnetite) settle out where current slows, concentrating in stream gravels (placers).",source:"original",productSafe:true},
  {id:63,domain:"economic",topic:"Resources",difficulty:"medium",q:"The key difference between a 'reserve' and a 'resource' is that a reserve is:",choices:["Always larger","The portion that is economically and legally extractable now","Purely hypothetical","Only offshore"],answer:1,explain:"Resources include all identified plus undiscovered material; reserves are the subset that is currently economic and legal to extract.",source:"original",productSafe:true},

  // ===== GENERAL & FIELD GEOLOGY (incl. ethics, maps, dating) =====
  {id:64,domain:"general",topic:"Ethics",difficulty:"medium",q:"Under most state geology licensing codes, a professional geologist's foremost obligation is to:",choices:["Maximize the client's profit","Protect public health, safety, and welfare","Always agree with the regulator","Finish the work as fast as possible"],answer:1,explain:"Licensure exists to protect the public; safeguarding public health, safety, and welfare is the paramount professional duty.",source:"original",productSafe:true},
  {id:65,domain:"general",topic:"Ethics",difficulty:"medium",q:"A geologist asked to stamp/seal a report they did not prepare or directly supervise should:",choices:["Sign it as a professional courtesy","Decline; the seal certifies your own responsible work","Sign only if paid extra","Sign if an engineer also signs"],answer:1,explain:"Sealing certifies the work was done by or under the responsible charge of the sealing geologist; sealing others' work is an ethics violation.",source:"original",productSafe:true},
  {id:66,domain:"general",topic:"Ethics",difficulty:"easy",q:"Practicing 'within one's area of competence' means a geologist should:",choices:["Accept any assignment offered","Perform only work for which they have adequate training and experience","Never subcontract specialists","Refuse all unfamiliar work permanently"],answer:1,explain:"Geologists must limit practice to areas where they are qualified, bringing in qualified specialists when needed.",source:"original",productSafe:true},
  {id:67,domain:"general",topic:"Maps",difficulty:"medium",q:"On a 1:24,000 topographic map, a map distance of 3 inches equals a ground distance of about:",choices:["6,000 ft","2,000 ft","72 ft","12,000 ft"],answer:0,explain:"3 in x 24,000 = 72,000 in; 72,000 / 12 = 6,000 ft.",source:"original",productSafe:true},
  {id:68,domain:"general",topic:"Maps",difficulty:"medium",q:"Short tick marks (hachures) pointing inward from a closed contour line indicate:",choices:["A hilltop","A closed depression (e.g., sinkhole or crater)","A vertical cliff","A spring"],answer:1,explain:"Hachured contours mark a depression where elevation decreases inward.",source:"original",productSafe:true},
  {id:69,domain:"general",topic:"Calculations",difficulty:"easy",q:"A slope rises 150 ft over a horizontal distance of 1,000 ft. Its gradient (percent slope) is about:",choices:["15%","1.5%","6.7%","150%"],answer:0,explain:"Percent slope = (rise/run) x 100 = (150/1,000) x 100 = 15%.",source:"original",productSafe:true},
  {id:70,domain:"general",topic:"Relative dating",difficulty:"hard",q:"A sandstone contains rounded fragments of the granite directly beneath it. By the principle of inclusions, the granite is:",choices:["Younger than the sandstone","Older than the sandstone","The same age as the sandstone","Impossible to date relatively"],answer:1,explain:"Fragments must come from a pre-existing rock, so the granite is older than the sandstone that contains its pieces.",source:"original",productSafe:true},
  {id:71,domain:"general",topic:"Relative dating",difficulty:"hard",q:"A chilled, baked contact zone where an igneous body meets sedimentary rock indicates the igneous body is:",choices:["Older than the sediment","Younger (it intruded or flowed against pre-existing rock)","The same age","A sedimentary deposit"],answer:1,explain:"A baked margin means the hot igneous body contacted already-existing rock, so it is younger (cross-cutting / baked-contact relationship).",source:"original",productSafe:true},
  {id:72,domain:"general",topic:"Principles",difficulty:"easy",q:"Uniformitarianism is the principle that:",choices:["Earth is unchanging","Present-day processes operated in much the same way in the past ('the present is the key to the past')","All rock forms catastrophically","Geologic time cannot be measured"],answer:1,explain:"Observable modern processes (erosion, deposition, etc.) are used to interpret the rock record.",source:"original",productSafe:true},
  {id:73,domain:"general",topic:"Field methods",difficulty:"medium",q:"A bed strikes N30E and dips 40SE. Its dip direction is toward the:",choices:["Northwest","Southeast","Northeast","Southwest"],answer:1,explain:"Dip is perpendicular to strike; here the bed inclines down toward the southeast.",source:"original",productSafe:true},
  {id:74,domain:"general",topic:"Field methods",difficulty:"hard",q:"An apparent dip measured on a cliff face oblique to the true dip direction is always:",choices:["Greater than the true dip","Equal to the true dip","Less than or equal to the true dip","Vertical"],answer:2,explain:"The maximum (true) dip is in the dip direction; any oblique cross-section shows an apparent dip that is equal to or less than true dip.",source:"original",productSafe:true},
  {id:75,domain:"general",topic:"Earth structure",difficulty:"medium",q:"The asthenosphere is best described as:",choices:["The rigid outer plates","A weak, ductile (partially molten) layer of the upper mantle on which plates move","The liquid outer core","The continental crust"],answer:1,explain:"The asthenosphere flows plastically over geologic time, allowing the rigid lithospheric plates above to move.",source:"original",productSafe:true},

  // ===== MINERALOGY, PETROLOGY & GEOCHEMISTRY =====
  {id:76,domain:"mineralogy",topic:"Mineral ID",difficulty:"hard",q:"Plagioclase feldspar is most reliably distinguished from K-feldspar by its:",choices:["Cubic cleavage","Polysynthetic (albite) twinning, seen as fine striations on cleavage faces","Strong magnetism","Effervescence in acid"],answer:1,explain:"Plagioclase commonly shows polysynthetic twinning striations; K-feldspar does not.",source:"original",productSafe:true},
  {id:77,domain:"mineralogy",topic:"Igneous texture",difficulty:"medium",q:"An aphanitic (fine-grained) igneous texture indicates:",choices:["Slow cooling deep underground","Rapid cooling at or near the surface","Metamorphic recrystallization","Chemical precipitation"],answer:1,explain:"Fast cooling gives crystals little time to grow, producing fine grains; slow (deep) cooling gives coarse, phaneritic textures.",source:"original",productSafe:true},
  {id:78,domain:"mineralogy",topic:"Igneous texture",difficulty:"hard",q:"A porphyritic texture (large crystals set in a fine-grained matrix) records:",choices:["A single, rapid cooling event","Two-stage cooling: slow at depth, then rapid near the surface","Deposition by running water","Very high metamorphic grade"],answer:1,explain:"Large phenocrysts grew slowly at depth; the fine groundmass formed when the magma later cooled quickly.",source:"original",productSafe:true},
  {id:79,domain:"mineralogy",topic:"Igneous rocks",difficulty:"medium",q:"Which is a coarse-grained (intrusive) rock of INTERMEDIATE composition?",choices:["Diorite","Basalt","Rhyolite","Obsidian"],answer:0,explain:"Diorite is the intrusive intermediate rock (andesite is its extrusive equivalent). Basalt is mafic extrusive; rhyolite felsic extrusive.",source:"original",productSafe:true},
  {id:80,domain:"mineralogy",topic:"Metamorphism",difficulty:"hard",q:"Which sequence of Barrovian index minerals reflects INCREASING metamorphic grade in pelitic rocks?",choices:["Sillimanite to garnet to chlorite","Chlorite to biotite to garnet to staurolite to kyanite to sillimanite","Garnet to chlorite to biotite","Quartz to calcite to halite"],answer:1,explain:"The Barrovian zones progress chlorite -> biotite -> garnet -> staurolite -> kyanite -> sillimanite with rising temperature.",source:"original",productSafe:true},
  {id:81,domain:"mineralogy",topic:"Metamorphism",difficulty:"medium",q:"Contact metamorphism differs from regional metamorphism mainly because it is driven by:",choices:["Heat from a nearby intrusion, with little directed pressure","Continental collision over broad areas","Deep burial alone","Surface weathering"],answer:0,explain:"Contact (thermal) metamorphism is localized heating around an intrusion, producing non-foliated hornfels; regional metamorphism adds directed pressure over large areas.",source:"original",productSafe:true},
  {id:82,domain:"mineralogy",topic:"Geochemistry",difficulty:"medium",q:"After 3 half-lives, the fraction of the original radioactive parent isotope remaining is:",choices:["1/2","1/4","1/8","1/16"],answer:2,explain:"Each half-life halves the parent: (1/2)^3 = 1/8 (12.5%).",source:"original",productSafe:true},
  {id:83,domain:"mineralogy",topic:"Geochemistry",difficulty:"hard",q:"A mineral has a parent-to-daughter isotope ratio of 1:3 for a system with a 700-million-year half-life. Its approximate age is:",choices:["700 Ma","1,400 Ma","2,100 Ma","350 Ma"],answer:1,explain:"Parent makes up 1 of 4 atoms = 1/4 remaining = 2 half-lives = 2 x 700 = 1,400 Ma.",source:"original",productSafe:true},
  {id:84,domain:"mineralogy",topic:"Mineral ID",difficulty:"medium",q:"Streak (the color of a mineral's powder) is MOST diagnostic for:",choices:["Clear quartz","Many metallic/opaque minerals such as hematite (reddish-brown streak)","Transparent gemstones","All silicate minerals"],answer:1,explain:"Streak is most useful for opaque, often metallic minerals; hematite's reddish-brown streak is a classic example.",source:"original",productSafe:true},

  // ===== SEDIMENTOLOGY, STRATIGRAPHY & PALEONTOLOGY =====
  {id:85,domain:"sedimentary",topic:"Sequence",difficulty:"hard",q:"A marine transgression (rising relative sea level) typically produces a vertical succession that:",choices:["Coarsens upward as the shoreline advances seaward","Fines upward as deeper-water facies bury shallower ones","Shows no change in facies","Is entirely evaporite"],answer:1,explain:"As the sea moves landward, deeper-water (finer) sediments are deposited over shallower (coarser) ones, giving a fining-upward, retrogradational stack.",source:"original",productSafe:true},
  {id:86,domain:"sedimentary",topic:"Paleontology",difficulty:"medium",q:"The principle of faunal succession permits correlation because:",choices:["Fossils appear in random order","Fossil organisms succeed one another in a definite, recognizable order through time","All fossils are the same age everywhere","Fossils occur only in igneous rock"],answer:1,explain:"Because life evolved in a fixed sequence, the fossil content of strata identifies and correlates their relative age.",source:"original",productSafe:true},
  {id:87,domain:"sedimentary",topic:"Maturity",difficulty:"hard",q:"A texturally and mineralogically MATURE sandstone (quartz arenite) implies:",choices:["Rapid burial of fresh, angular debris","Prolonged weathering and transport that removed unstable grains, leaving rounded, well-sorted quartz","Direct glacial dumping","A volcanic origin"],answer:1,explain:"Maturity increases with weathering/transport: unstable minerals break down and grains become rounded and sorted, concentrating durable quartz.",source:"original",productSafe:true},
  {id:88,domain:"sedimentary",topic:"Carbonates",difficulty:"medium",q:"Most limestone forms by:",choices:["Mechanical accumulation of quartz sand","Biological and chemical precipitation of calcium carbonate, commonly in warm, shallow seas","Wind transport of silt","Metamorphism of basalt"],answer:1,explain:"Limestone is a biochemical/chemical carbonate rock; reefs, shells, and lime mud accumulate in warm shallow marine settings.",source:"original",productSafe:true},
  {id:89,domain:"sedimentary",topic:"Environments",difficulty:"hard",q:"A poorly sorted, matrix-supported diamictite containing striated and faceted clasts most likely indicates:",choices:["Beach deposition","Glacial (till) or debris-flow deposition","Eolian dune deposition","Deep-marine ooze"],answer:1,explain:"Lack of sorting plus striated clasts points to ice transport (glacial till) or sediment-gravity (debris) flow.",source:"original",productSafe:true},
  {id:90,domain:"sedimentary",topic:"Fossilization",difficulty:"medium",q:"A fossil preserved as a mold and cast formed when the original:",choices:["Was replaced mineral-by-mineral (petrified)","Dissolved to leave an impression (mold) that was later filled by sediment/mineral (cast)","Was frozen in ice","Was only carbonized to a film"],answer:1,explain:"Dissolution leaves a mold of the shape; infilling of that void produces a cast.",source:"original",productSafe:true},
  {id:91,domain:"sedimentary",topic:"Unconformities",difficulty:"hard",q:"Flat-lying sedimentary strata resting directly on eroded granite or metamorphic basement form a:",choices:["Disconformity","Angular unconformity","Nonconformity","Paraconformity"],answer:2,explain:"A nonconformity separates sedimentary rock above from eroded crystalline (igneous/metamorphic) rock below.",source:"original",productSafe:true},
  {id:92,domain:"sedimentary",topic:"Structures",difficulty:"medium",q:"Mud cracks together with symmetrical ripple marks most likely indicate:",choices:["Permanent deep-ocean conditions","Shallow water that alternately wetted and dried (e.g., tidal flat, playa)","Deep burial diagenesis","Active volcanism"],answer:1,explain:"Desiccation cracks require subaerial drying; with ripples they signal a shallow, periodically exposed environment.",source:"original",productSafe:true},
  {id:93,domain:"sedimentary",topic:"Paleontology",difficulty:"easy",q:"The Cambrian 'explosion' refers to:",choices:["The extinction of the dinosaurs","The rapid diversification of complex multicellular animals near the start of the Paleozoic","The formation of the Moon","The first appearance of land plants"],answer:1,explain:"Around 540 Ma, most major animal phyla appear in the fossil record over a geologically short interval.",source:"original",productSafe:true},

  // ===== GEOMORPHOLOGY & SURFICIAL PROCESSES =====
  {id:94,domain:"geomorph",topic:"Drainage",difficulty:"hard",q:"A dendritic (branching, tree-like) drainage pattern typically develops on:",choices:["Tilted alternating hard and soft beds","Relatively uniform, flat-lying or homogeneous rock","A single volcanic cone","Strongly jointed bedrock"],answer:1,explain:"Dendritic drainage forms where the substrate offers no strong structural control. Trellis = tilted alternating beds; radial = volcano; rectangular = joints.",source:"original",productSafe:true},
  {id:95,domain:"geomorph",topic:"Drainage",difficulty:"medium",q:"A trellis drainage pattern most often reflects:",choices:["Homogeneous flat-lying rock","Folded or tilted alternating resistant and weak strata","A volcanic cone","A flat plain"],answer:1,explain:"Tributaries follow weak beds and join trunk streams at near-right angles, recording folded/tilted layered rock.",source:"original",productSafe:true},
  {id:96,domain:"geomorph",topic:"Glacial",difficulty:"hard",q:"A long, sinuous ridge of sand and gravel deposited by a meltwater stream flowing within or beneath a glacier is a(n):",choices:["Esker","Drumlin","Terminal moraine","Cirque"],answer:0,explain:"Eskers are sediment casts of subglacial/englacial meltwater channels; drumlins are streamlined till hills.",source:"original",productSafe:true},
  {id:97,domain:"geomorph",topic:"Glacial",difficulty:"medium",q:"A bowl-shaped depression carved at the head of an alpine glacier is a:",choices:["Cirque","Kettle","Drumlin","Kame"],answer:0,explain:"A cirque is the amphitheater-shaped basin where an alpine glacier originates.",source:"original",productSafe:true},
  {id:98,domain:"geomorph",topic:"Glacial",difficulty:"medium",q:"A kettle (kettle lake) forms when:",choices:["A river meander is cut off","A buried block of stagnant ice melts, leaving a depression in outwash","A volcano collapses","Limestone dissolves"],answer:1,explain:"Ice blocks left in glacial outwash melt and the overlying/surrounding sediment collapses into the void, often filling with water.",source:"original",productSafe:true},
  {id:99,domain:"geomorph",topic:"Coastal",difficulty:"medium",q:"Longshore drift transports beach sediment:",choices:["Straight offshore into deep water","Along the shoreline, driven by waves approaching at an angle","Only inland during storms","Vertically downward"],answer:1,explain:"Obliquely breaking waves move sand in a zig-zag net direction parallel to the coast.",source:"original",productSafe:true},
  {id:100,domain:"geomorph",topic:"Weathering",difficulty:"easy",q:"Chemical weathering is generally MOST intense in climates that are:",choices:["Cold and dry","Warm and humid","Polar","Arid desert"],answer:1,explain:"Heat and abundant water accelerate chemical reactions (hydrolysis, dissolution, oxidation).",source:"original",productSafe:true},
  {id:101,domain:"geomorph",topic:"Fluvial",difficulty:"medium",q:"A stream's 'base level' is:",choices:["Its headwater elevation","The lowest elevation to which it can erode (ultimately sea level)","Its average channel width","Its flood-stage height"],answer:1,explain:"Streams cannot erode below base level; sea level is the ultimate base level for most rivers.",source:"original",productSafe:true},
  {id:102,domain:"geomorph",topic:"Quaternary",difficulty:"easy",q:"The Quaternary Period is best known for:",choices:["The origin of life","Repeated continental glaciations (ice ages) and human evolution","Assembly of Pangaea","The K-Pg mass extinction"],answer:1,explain:"The Quaternary (last ~2.6 Myr) features cyclic ice ages and the rise of modern humans.",source:"original",productSafe:true},

  // ===== STRUCTURE, TECTONICS & SEISMOLOGY =====
  {id:103,domain:"structure",topic:"Deformation",difficulty:"hard",q:"Rocks deform in a BRITTLE manner (fracturing) rather than ductile (flowing) when conditions are:",choices:["High temperature and pressure deep in the crust","Low temperature and pressure at shallow depth, with rapid strain","Within the asthenosphere","Independent of depth"],answer:1,explain:"Shallow, cool, fast-strained rock fractures; deeper, hotter, slowly strained rock flows ductilely.",source:"original",productSafe:true},
  {id:104,domain:"structure",topic:"Faults",difficulty:"hard",q:"Facing a strike-slip fault, the block on the far side moves to your right. The fault is:",choices:["Left-lateral (sinistral)","Right-lateral (dextral)","Normal","Reverse"],answer:1,explain:"If the opposite side shifts right regardless of which side you stand on, it is right-lateral (dextral), like the San Andreas.",source:"original",productSafe:true},
  {id:105,domain:"structure",topic:"Faults",difficulty:"medium",q:"A low-angle (<30 degrees) reverse fault that places older rocks over younger rocks is a:",choices:["Normal fault","Thrust fault","Transform fault","Graben"],answer:1,explain:"Thrust faults are low-angle compressional reverse faults that can stack older rock atop younger rock.",source:"original",productSafe:true},
  {id:106,domain:"structure",topic:"Folds",difficulty:"hard",q:"An overturned fold is characterized by:",choices:["Both limbs dipping away from each other","Both limbs dipping in the same direction (one limb rotated past vertical)","No limbs","A perfectly horizontal axial plane only"],answer:1,explain:"In an overturned fold the axial plane is inclined enough that one limb is tilted beyond vertical, so both limbs dip the same way.",source:"original",productSafe:true},
  {id:107,domain:"structure",topic:"Tectonics",difficulty:"medium",q:"Symmetrical linear magnetic 'stripes' on either side of a mid-ocean ridge are evidence for:",choices:["Meteorite impacts","Seafloor spreading recorded by geomagnetic reversals","Continental glaciation","Volcanic ash falls"],answer:1,explain:"New crust records the magnetic polarity at the time it forms; the symmetric reversal pattern proved seafloor spreading.",source:"original",productSafe:true},
  {id:108,domain:"structure",topic:"Tectonics",difficulty:"medium",q:"A chain of volcanoes that grows progressively older away from one active volcano (e.g., Hawaii) records:",choices:["A subduction zone","A relatively fixed mantle hotspot beneath a moving plate","A transform fault","A spreading ridge"],answer:1,explain:"As the plate moves over a stationary mantle plume, a track of increasingly older, extinct volcanoes forms.",source:"original",productSafe:true},
  {id:109,domain:"structure",topic:"Isostasy",difficulty:"hard",q:"Isostasy explains why:",choices:["High mountains are underlain by deep, low-density crustal 'roots'","Oceans are salty","All earthquakes are shallow","Rocks melt at depth"],answer:0,explain:"Crust floats on the denser mantle; thick, buoyant crust stands high and projects a deep root, like an iceberg.",source:"original",productSafe:true},
  {id:110,domain:"structure",topic:"Seismology",difficulty:"hard",q:"Because the magnitude scale is logarithmic, a magnitude 7 earthquake produces ground-shaking amplitudes about ___ those of a magnitude 5:",choices:["2 times","10 times","100 times","1,000 times"],answer:2,explain:"Each whole magnitude unit is a 10x increase in amplitude, so two units = 10 x 10 = 100x.",source:"original",productSafe:true},

  // ===== HYDROGEOLOGY =====
  {id:111,domain:"hydro",topic:"Gradient",difficulty:"medium",q:"Two wells 400 m apart have water-table elevations of 52 m and 48 m. The hydraulic gradient is:",choices:["0.01","0.04","0.1","1.0"],answer:0,explain:"i = dh/dL = (52 - 48)/400 = 4/400 = 0.01.",source:"original",productSafe:true},
  {id:112,domain:"hydro",topic:"Darcy's law",difficulty:"hard",q:"Using Q = K i A with K = 20 m/day, i = 0.01, and A = 100 m^2, the discharge Q is:",choices:["20 m^3/day","2 m^3/day","200 m^3/day","0.2 m^3/day"],answer:0,explain:"Q = 20 x 0.01 x 100 = 20 m^3/day.",source:"original",productSafe:true},
  {id:113,domain:"hydro",topic:"Velocity",difficulty:"hard",q:"If the Darcy (specific discharge) velocity is 0.5 m/day in a sand with porosity 0.25, the average linear (seepage) velocity is:",choices:["0.125 m/day","2 m/day","0.5 m/day","5 m/day"],answer:1,explain:"Seepage velocity = Darcy velocity / porosity = 0.5 / 0.25 = 2 m/day (water moves faster than the bulk flux because it threads only the pores).",source:"original",productSafe:true},
  {id:114,domain:"hydro",topic:"Transmissivity",difficulty:"medium",q:"An aquifer 25 m thick has a hydraulic conductivity of 12 m/day. Its transmissivity is:",choices:["300 m^2/day","37 m^2/day","2.1 m^2/day","12 m^2/day"],answer:0,explain:"T = K x b = 12 x 25 = 300 m^2/day.",source:"original",productSafe:true},
  {id:115,domain:"hydro",topic:"Conductivity",difficulty:"easy",q:"Which material typically has the HIGHEST hydraulic conductivity?",choices:["Clay","Silt","Clean gravel","Unfractured granite"],answer:2,explain:"Large, well-connected pores in clean gravel transmit water readily; clay and intact crystalline rock are nearly impermeable.",source:"original",productSafe:true},
  {id:116,domain:"hydro",topic:"Coastal",difficulty:"hard",q:"Per the Ghyben-Herzberg relationship, over-pumping a coastal freshwater aquifer commonly causes:",choices:["Land uplift","Saltwater intrusion (upconing of the salt-fresh interface toward the well)","Increased recharge","A drop in salinity"],answer:1,explain:"Lowering the freshwater head reduces the pressure holding back denser seawater, drawing the saltwater interface upward/inland.",source:"original",productSafe:true},
  {id:117,domain:"hydro",topic:"Contaminants",difficulty:"hard",q:"A dense non-aqueous phase liquid (DNAPL) such as trichloroethylene (TCE) released to an aquifer tends to:",choices:["Float on the water table","Sink through the water and pool at the base of the aquifer","Evaporate instantly","Remain at the ground surface"],answer:1,explain:"DNAPLs are denser than water, so they migrate downward and collect on low-permeability layers, making cleanup difficult.",source:"original",productSafe:true},
  {id:118,domain:"hydro",topic:"Contaminants",difficulty:"medium",q:"A light non-aqueous phase liquid (LNAPL) such as gasoline will mainly:",choices:["Sink to the aquifer base","Float on and spread along the top of the water table","Dissolve completely and vanish","Convert entirely to gas"],answer:1,explain:"LNAPLs are less dense than water, so they spread as a layer riding on the water table.",source:"original",productSafe:true},
  {id:119,domain:"hydro",topic:"Wells",difficulty:"hard",q:"For a given pumping rate, the cone of depression will be deepest and steepest in an aquifer with:",choices:["High transmissivity","Low transmissivity","Unlimited recharge","High porosity but unlimited supply"],answer:1,explain:"A low-transmissivity aquifer cannot deliver water easily, so larger drawdown (a deeper, steeper cone) is needed to sustain pumping.",source:"original",productSafe:true},
  {id:120,domain:"hydro",topic:"Zones",difficulty:"easy",q:"The zone above the water table, where pore spaces hold both air and water, is the:",choices:["Phreatic (saturated) zone","Vadose (unsaturated) zone","Confined aquifer","Aquiclude"],answer:1,explain:"The vadose (unsaturated) zone lies between the ground surface and the water table.",source:"original",productSafe:true},
  {id:121,domain:"hydro",topic:"Artesian",difficulty:"medium",q:"A FLOWING artesian well occurs where the potentiometric surface of a confined aquifer is:",choices:["Below the aquifer","Above the ground surface at the well location","Exactly at the water table","Undefined"],answer:1,explain:"If the potentiometric (pressure) surface rises above ground level, water flows out at the surface without pumping.",source:"original",productSafe:true},
  {id:122,domain:"hydro",topic:"Recharge",difficulty:"medium",q:"Natural groundwater recharge is generally GREATEST where:",choices:["Surfaces are paved and impermeable","Permeable soils receive precipitation with little runoff or evaporation","There is essentially no rainfall","Steep clay slopes shed water"],answer:1,explain:"Infiltration is favored by permeable ground, ample precipitation, gentle slopes, and low evapotranspiration.",source:"original",productSafe:true},

  // ===== ENGINEERING GEOLOGY =====
  {id:123,domain:"engineering",topic:"Effective stress",difficulty:"medium",q:"At a point the total vertical stress is 200 kPa and the pore-water pressure is 100 kPa. The effective stress is:",choices:["300 kPa","100 kPa","2 kPa","0 kPa"],answer:1,explain:"Effective stress sigma' = sigma - u = 200 - 100 = 100 kPa.",source:"original",productSafe:true},
  {id:124,domain:"engineering",topic:"Slope stability",difficulty:"medium",q:"A slope has resisting forces of 1,800 and driving forces of 1,200 (same units). Its factor of safety is:",choices:["0.67","1.5","3.0","600"],answer:1,explain:"FS = resisting/driving = 1,800/1,200 = 1.5 (FS < 1 means failure).",source:"original",productSafe:true},
  {id:125,domain:"engineering",topic:"Rock mass",difficulty:"medium",q:"A 100-cm core run yields intact pieces 10 cm or longer totaling 75 cm. The Rock Quality Designation (RQD) is:",choices:["75%","10%","100%","7.5%"],answer:0,explain:"RQD = (sum of pieces >= 10 cm / total run) x 100 = 75/100 x 100 = 75%.",source:"original",productSafe:true},
  {id:126,domain:"engineering",topic:"Shear strength",difficulty:"hard",q:"In the Mohr-Coulomb relation tau = c + sigma' tan(phi), raising pore-water pressure (which lowers sigma') will:",choices:["Increase shear strength","Decrease shear strength","Have no effect on strength","Increase cohesion"],answer:1,explain:"Higher pore pressure reduces effective normal stress, lowering frictional resistance and thus shear strength, a key driver of slope failure.",source:"original",productSafe:true},
  {id:127,domain:"engineering",topic:"Soil classification",difficulty:"hard",q:"In the Unified Soil Classification System (USCS), the symbol 'CH' denotes:",choices:["Clean, well-graded gravel","High-plasticity (fat) clay","Poorly graded sand","Organic peat"],answer:1,explain:"C = clay, H = high plasticity (liquid limit > 50). 'CL' would be low-plasticity clay.",source:"original",productSafe:true},
  {id:128,domain:"engineering",topic:"Consolidation",difficulty:"medium",q:"Settlement of a saturated clay under a new building load occurs SLOWLY because:",choices:["Clay is highly permeable","Low permeability delays drainage of pore water (consolidation)","Clay is perfectly rigid","No water is present"],answer:1,explain:"Load is initially carried by pore water; as the low-permeability clay slowly drains, the soil skeleton compresses (primary consolidation).",source:"original",productSafe:true},
  {id:129,domain:"engineering",topic:"Liquefaction",difficulty:"medium",q:"Liquefaction during shaking is GREATEST risk for:",choices:["Dense gravel above the water table","Loose, saturated, uniform fine sand","Dry stiff clay","Intact bedrock"],answer:1,explain:"Loose saturated sands lose strength when shaking raises pore pressure until grains lose contact.",source:"original",productSafe:true},
  {id:130,domain:"engineering",topic:"Expansive soils",difficulty:"medium",q:"Foundation and slab damage from expansive soils is caused mainly by:",choices:["Freeze-thaw of gravel","Shrink-swell of smectite (montmorillonite) clays with moisture changes","Quartz hardness","Salt crystallization only"],answer:1,explain:"Smectite clays expand when wetted and shrink when dried, heaving and cracking structures.",source:"original",productSafe:true},
  {id:131,domain:"engineering",topic:"Field testing",difficulty:"medium",q:"In the Standard Penetration Test (SPT), a higher N-value (blow count) generally indicates:",choices:["Looser or softer soil","Denser or stiffer soil","Higher water content","Lower bearing capacity"],answer:1,explain:"More blows to drive the sampler means a denser, stronger soil with higher bearing capacity.",source:"original",productSafe:true},
  {id:132,domain:"engineering",topic:"Geohazards",difficulty:"medium",q:"The principal geologic hazard when developing over buried limestone karst is:",choices:["Liquefaction","Sinkhole collapse","Volcanic eruption","Glacial rebound"],answer:1,explain:"Dissolution cavities in karst can collapse, producing sinkholes beneath structures.",source:"original",productSafe:true},

  // ===== ECONOMIC GEOLOGY & ENERGY =====
  {id:133,domain:"economic",topic:"Petroleum",difficulty:"medium",q:"In a petroleum system, the unit that prevents hydrocarbons from leaking upward out of the reservoir is the:",choices:["Source rock","Reservoir rock","Seal (cap rock)","Crystalline basement"],answer:2,explain:"An impermeable seal (e.g., shale, salt) caps the porous reservoir and, with a trap geometry, retains the hydrocarbons.",source:"original",productSafe:true},
  {id:134,domain:"economic",topic:"Petroleum",difficulty:"hard",q:"An anticlinal trap holds hydrocarbons because:",choices:["Gravity drives oil down into the crest","Buoyant oil and gas migrate up-dip and are trapped beneath the seal at the fold crest","Oil is denser than water","Faults always leak"],answer:1,explain:"Oil and gas are buoyant and rise until stopped; the arch of an anticline with a sealing cap concentrates them at the crest.",source:"original",productSafe:true},
  {id:135,domain:"economic",topic:"Coal",difficulty:"easy",q:"The highest-rank coal, with the greatest carbon content and heat value, is:",choices:["Peat","Lignite","Bituminous","Anthracite"],answer:3,explain:"Increasing rank: peat -> lignite -> bituminous -> anthracite (highest carbon, hardest, hottest-burning).",source:"original",productSafe:true},
  {id:136,domain:"economic",topic:"Ore deposits",difficulty:"hard",q:"Mississippi Valley-type (MVT) lead-zinc deposits are hosted primarily in:",choices:["Granite","Carbonate (limestone/dolostone) rocks","Basalt flows","Coal seams"],answer:1,explain:"MVT deposits form from warm basinal brines precipitating sulfides in carbonate host rocks, away from igneous activity.",source:"original",productSafe:true},
  {id:137,domain:"economic",topic:"Ore deposits",difficulty:"hard",q:"Banded iron formations (BIFs), the world's primary iron ore, formed mainly during the:",choices:["Cenozoic","Precambrian, tied to early ocean chemistry and rising oxygen","Modern desert environments","Recent glaciations"],answer:1,explain:"Most BIFs precipitated in Precambrian oceans as dissolved iron was oxidized during the Great Oxygenation Event.",source:"original",productSafe:true},
  {id:138,domain:"economic",topic:"Resources",difficulty:"medium",q:"Evaporite deposits such as halite and gypsum form by:",choices:["Volcanic eruption","Evaporation of restricted or saline water bodies","Glacial grinding","Metamorphism of shale"],answer:1,explain:"As saline water evaporates, dissolved salts precipitate in sequence (e.g., gypsum then halite), forming evaporite beds.",source:"original",productSafe:true},
];
