// Liana's ASBOG FG study bank.
// PROVENANCE: every item is tagged. source:"original" = written from scratch to the
// ASBOG FG content domains (safe for a future product). productSafe:true = OK to ship.
// If publisher/copyrighted questions (Mometrix, etc.) are ever added, tag them
// source:"<publisher>" and productSafe:false so the product build filters them out.
// Schema: {id, domain, topic, difficulty, q, choices:[4], answer:<idx>, explain, source, productSafe}
window.GEO_DOMAINS = [
  { key:"general",   name:"General & Field Geology",
    blurb:"Maps, strike/dip, dating principles, field methods, basic Earth science.",
    resources:[
      ["Physical Geology (Earle) — Ch.1 & Geologic Time","https://opentextbc.ca/physicalgeology2ed/"],
      ["USGS — Topographic maps","https://www.usgs.gov/programs/national-geospatial-program/topographic-maps"]]},
  { key:"mineralogy", name:"Mineralogy, Petrology & Geochemistry",
    blurb:"Minerals, igneous/metamorphic rocks, Bowen's series, isotopes.",
    resources:[
      ["Physical Geology (Earle) — Minerals & Igneous Rocks","https://opentextbc.ca/physicalgeology2ed/"],
      ["USGS — Minerals","https://www.usgs.gov/programs/mineral-resources-program"]]},
  { key:"sedimentary", name:"Sedimentology, Stratigraphy & Paleontology",
    blurb:"Clastic/chemical sediments, depositional environments, correlation, fossils.",
    resources:[["Physical Geology (Earle) — Sedimentary Rocks","https://opentextbc.ca/physicalgeology2ed/"]]},
  { key:"geomorph",  name:"Geomorphology & Surficial Processes",
    blurb:"Weathering, soils, rivers, glaciers, coasts, mass wasting, Quaternary.",
    resources:[["Physical Geology (Earle) — Streams/Glaciers/Mass Wasting","https://opentextbc.ca/physicalgeology2ed/"]]},
  { key:"structure", name:"Structure, Tectonics & Seismology",
    blurb:"Folds, faults, plate boundaries, earthquakes, seismic waves.",
    resources:[
      ["Physical Geology (Earle) — Plate Tectonics & Structures","https://opentextbc.ca/physicalgeology2ed/"],
      ["USGS Earthquake Hazards","https://earthquake.usgs.gov/"]]},
  { key:"hydro",     name:"Hydrogeology",
    blurb:"Porosity/permeability, Darcy's law, aquifers, wells, contaminant transport.",
    resources:[
      ["Physical Geology (Earle) — Groundwater","https://opentextbc.ca/physicalgeology2ed/"],
      ["USGS Water Resources","https://www.usgs.gov/mission-areas/water-resources"]]},
  { key:"engineering", name:"Engineering Geology",
    blurb:"Soil/rock mechanics, slope stability, foundations, liquefaction, geohazards.",
    resources:[["USGS Landslide Hazards","https://www.usgs.gov/programs/landslide-hazards"]]},
  { key:"economic",  name:"Economic Geology & Energy",
    blurb:"Ore deposits, petroleum systems, coal, resources vs reserves.",
    resources:[["USGS Energy Resources","https://www.usgs.gov/programs/energy-resources-program"]]},
];

window.GEO_QUESTIONS = [
  // ===== GENERAL & FIELD GEOLOGY =====
  {id:1,domain:"general",topic:"Field methods",difficulty:"medium",q:"In a geologic 'strike and dip' measurement, the DIP is:",choices:["The compass bearing of a horizontal line on the bed","The angle the bed makes below horizontal, measured perpendicular to strike","The thickness of the bed","The depth to the bed"],answer:1,explain:"Strike is the bearing of a horizontal line on the inclined plane; dip is the maximum angle of inclination below horizontal, measured at 90° to strike.",source:"original",productSafe:true},
  {id:2,domain:"general",topic:"Topographic maps",difficulty:"easy",q:"On a topographic map, contour lines spaced very close together indicate:",choices:["A gentle slope","A steep slope","Flat ground","A depression"],answer:1,explain:"Closely spaced contours = rapid elevation change = steep slope. Widely spaced = gentle.",source:"original",productSafe:true},
  {id:3,domain:"general",topic:"Topographic maps",difficulty:"medium",q:"Where contour lines cross a stream valley, the 'V' of the contours points:",choices:["Downstream","Upstream","Always north","Toward the nearest peak"],answer:1,explain:"Contours bend upstream (uphill) as they cross a valley, so the V points upstream.",source:"original",productSafe:true},
  {id:4,domain:"general",topic:"Relative dating",difficulty:"easy",q:"The principle of cross-cutting relationships states that:",choices:["A fault or intrusion is younger than the rocks it cuts","The bottom layer is always igneous","Fossils get younger downward","Folds form before deposition"],answer:0,explain:"Any feature that cuts across another (fault, dike, intrusion) must be younger than what it disrupts.",source:"original",productSafe:true},
  {id:5,domain:"general",topic:"Relative dating",difficulty:"easy",q:"Steno's principle of original horizontality states that sedimentary layers are originally deposited:",choices:["Vertically","At random angles","Horizontally (or nearly so)","Only on slopes"],answer:2,explain:"Sediments settle under gravity into roughly horizontal layers; tilted beds were deformed after deposition.",source:"original",productSafe:true},
  {id:6,domain:"general",topic:"Map scale",difficulty:"medium",q:"A map at a scale of 1:24,000 means one inch on the map equals about:",choices:["24,000 inches (≈2,000 ft)","24,000 miles","240 ft","24 ft"],answer:0,explain:"1:24,000 means 1 unit on the map = 24,000 units on the ground; 24,000 in ≈ 2,000 ft. This is the standard USGS quadrangle scale.",source:"original",productSafe:true},
  {id:7,domain:"general",topic:"Dating",difficulty:"medium",q:"Relative dating differs from absolute (numerical) dating in that relative dating:",choices:["Gives an age in years","Establishes age order/sequence without exact years","Requires radioactive isotopes","Only works on fossils"],answer:1,explain:"Relative dating orders events (older/younger) using principles like superposition; absolute dating assigns numeric ages (e.g., via isotopes).",source:"original",productSafe:true},
  {id:8,domain:"general",topic:"Geologic time",difficulty:"easy",q:"Non-avian dinosaurs dominated land during which era?",choices:["Paleozoic","Mesozoic","Cenozoic","Precambrian"],answer:1,explain:"The Mesozoic (Triassic–Jurassic–Cretaceous) ended ~66 Ma at the K-Pg extinction; mammals radiated in the following Cenozoic.",source:"original",productSafe:true},
  {id:9,domain:"general",topic:"Earth structure",difficulty:"medium",q:"Which Earth layer is interpreted as LIQUID based on the S-wave shadow zone?",choices:["Inner core","Outer core","Lower mantle","Crust"],answer:1,explain:"S-waves cannot pass through liquid, so they are blocked by the liquid outer core, producing the S-wave shadow zone. The inner core is solid.",source:"original",productSafe:true},
  {id:10,domain:"general",topic:"Field safety/ethics",difficulty:"easy",q:"A licensed professional geologist's stamp/seal on a report primarily certifies that:",choices:["The work meets professional standards and the geologist takes responsibility for it","The client approved the budget","The data are guaranteed error-free forever","The report is copyrighted"],answer:0,explain:"The seal signifies the work was done by/under a licensed PG to accepted professional standards, with accountability for protecting public welfare.",source:"original",productSafe:true},

  // ===== MINERALOGY, PETROLOGY & GEOCHEMISTRY =====
  {id:11,domain:"mineralogy",topic:"Mineral ID",difficulty:"easy",q:"On the Mohs hardness scale, which mineral defines a hardness of 7?",choices:["Talc","Calcite","Quartz","Topaz"],answer:2,explain:"Quartz = 7 (talc 1, calcite 3, topaz 8). Quartz scratches glass and steel.",source:"original",productSafe:true},
  {id:12,domain:"mineralogy",topic:"Mineral ID",difficulty:"easy",q:"Which simple field test best distinguishes calcite from quartz?",choices:["Calcite fizzes (effervesces) with dilute HCl","Calcite is magnetic","Calcite is heavier","Quartz dissolves in water"],answer:0,explain:"Calcite (a carbonate) reacts with dilute HCl, releasing CO2 bubbles; quartz does not react.",source:"original",productSafe:true},
  {id:13,domain:"mineralogy",topic:"Crystal chemistry",difficulty:"hard",q:"Quartz (SiO2) is classified as which silicate structure?",choices:["Isolated tetrahedra (nesosilicate)","Single chain (inosilicate)","Sheet (phyllosilicate)","Framework (tectosilicate)"],answer:3,explain:"In quartz every oxygen is shared between two tetrahedra (3-D framework), giving the 1:2 Si:O ratio. Olivine = neso-, pyroxene = single-chain, mica = sheet.",source:"original",productSafe:true},
  {id:14,domain:"mineralogy",topic:"Igneous",difficulty:"medium",q:"According to Bowen's reaction series, which mineral crystallizes at the HIGHEST temperature?",choices:["Quartz","Muscovite","Olivine","K-feldspar"],answer:2,explain:"Olivine is at the high-temperature top of the discontinuous series; quartz, muscovite, and K-feldspar form last (lowest T).",source:"original",productSafe:true},
  {id:15,domain:"mineralogy",topic:"Igneous",difficulty:"easy",q:"The fine-grained extrusive equivalent of granite is:",choices:["Basalt","Gabbro","Rhyolite","Andesite"],answer:2,explain:"Rhyolite shares granite's felsic composition but cools rapidly at the surface. Gabbro = mafic intrusive, basalt = mafic extrusive.",source:"original",productSafe:true},
  {id:16,domain:"mineralogy",topic:"Igneous",difficulty:"easy",q:"A mafic igneous rock is:",choices:["High-silica, light, quartz-rich","Low-silica, dark, Fe-Mg-rich","Always glassy","Carbonate-rich"],answer:1,explain:"Mafic = low silica, dark, rich in iron/magnesium minerals (basalt/gabbro). Felsic is the high-silica, light counterpart.",source:"original",productSafe:true},
  {id:17,domain:"mineralogy",topic:"Metamorphic",difficulty:"medium",q:"Which lists foliated metamorphic rocks in order of INCREASING grade?",choices:["Gneiss → schist → phyllite → slate","Slate → phyllite → schist → gneiss","Schist → slate → gneiss → phyllite","Phyllite → slate → schist → gneiss"],answer:1,explain:"Increasing T/P: slate → phyllite → schist → gneiss, with coarsening grain size and mineral banding.",source:"original",productSafe:true},
  {id:18,domain:"mineralogy",topic:"Metamorphic",difficulty:"easy",q:"Marble forms by metamorphism of:",choices:["Sandstone","Limestone/dolostone","Shale","Basalt"],answer:1,explain:"Marble = metamorphosed carbonate. Quartzite ← sandstone, slate/schist ← shale.",source:"original",productSafe:true},
  {id:19,domain:"mineralogy",topic:"Geochemistry",difficulty:"medium",q:"Radiocarbon (¹⁴C) dating is appropriate for organic materials up to roughly:",choices:["~50,000 years","~500 million years","~4.6 billion years","~100 years only"],answer:0,explain:"With a ~5,730-yr half-life, ¹⁴C is useful to ~50 ka. Older materials need U-Pb, K-Ar, etc.",source:"original",productSafe:true},

  // ===== SEDIMENTOLOGY, STRATIGRAPHY & PALEONTOLOGY =====
  {id:20,domain:"sedimentary",topic:"Clastics",difficulty:"easy",q:"Which clastic sediment has the LARGEST grain size?",choices:["Clay","Silt","Sand","Gravel"],answer:3,explain:"Wentworth scale: gravel (>2 mm) > sand > silt > clay (finest).",source:"original",productSafe:true},
  {id:21,domain:"sedimentary",topic:"Texture",difficulty:"medium",q:"Well-rounded, well-sorted sand grains indicate:",choices:["Very short transport","Extensive transport/reworking","Glacial till","Chemical precipitation"],answer:1,explain:"Rounding and sorting increase with transport distance and energy; glacial till is angular and poorly sorted.",source:"original",productSafe:true},
  {id:22,domain:"sedimentary",topic:"Structures",difficulty:"medium",q:"Cross-bedding is most useful for interpreting:",choices:["Paleocurrent direction","Absolute age","Metamorphic grade","Magnetic reversals"],answer:0,explain:"Cross-bed foresets dip down-current, recording flow direction and environment (dunes/ripples).",source:"original",productSafe:true},
  {id:23,domain:"sedimentary",topic:"Way-up indicators",difficulty:"hard",q:"In a turbidite, graded bedding (coarse at base fining upward) is used to determine:",choices:["The stratigraphic 'way up' (which side was originally up)","The exact age","The water depth in meters","The magnetic field"],answer:0,explain:"Normal grading fines upward, so the coarse end marks the original bottom, a key way-up indicator in deformed strata.",source:"original",productSafe:true},
  {id:24,domain:"sedimentary",topic:"Stratigraphy",difficulty:"easy",q:"The principle of superposition states that in an undeformed sequence:",choices:["Younger layers lie below older","Older at bottom, younger on top","All layers are the same age","Layers form vertically"],answer:1,explain:"Each undisturbed layer is younger than the one beneath it.",source:"original",productSafe:true},
  {id:25,domain:"sedimentary",topic:"Unconformities",difficulty:"hard",q:"An angular unconformity is:",choices:["Two parallel conformable beds","Tilted/folded older rocks eroded and overlain by flat-lying younger strata","An igneous sill","A fault contact"],answer:1,explain:"Older beds were tilted and eroded, then younger flat beds deposited on top (angular discordance). Disconformity = parallel; nonconformity = strata on eroded crystalline basement.",source:"original",productSafe:true},
  {id:26,domain:"sedimentary",topic:"Paleontology",difficulty:"easy",q:"A good index (guide) fossil is:",choices:["Geographically restricted and long-lived","Widespread but short-lived","Only in igneous rocks","Still alive today"],answer:1,explain:"Widespread (for correlation) and short time range (for precision). Both are required.",source:"original",productSafe:true},
  {id:27,domain:"sedimentary",topic:"Facies",difficulty:"hard",q:"Walther's Law states that facies occurring in a conformable vertical succession also:",choices:["Occurred side-by-side laterally in adjacent environments","Are all the same age","Indicate a mass extinction","Formed by metamorphism"],answer:0,explain:"Vertically stacked conformable facies represent laterally adjacent depositional environments that migrated over time.",source:"original",productSafe:true},

  // ===== GEOMORPHOLOGY & SURFICIAL PROCESSES =====
  {id:28,domain:"geomorph",topic:"Glacial",difficulty:"easy",q:"A broad U-shaped valley is most diagnostic of erosion by:",choices:["A river","A glacier","Wind","Groundwater"],answer:1,explain:"Glaciers carve flat-bottomed, steep-walled U-shaped valleys; rivers cut V-shaped valleys.",source:"original",productSafe:true},
  {id:29,domain:"geomorph",topic:"Glacial",difficulty:"medium",q:"An unsorted, unstratified glacial sediment deposited directly by ice is called:",choices:["Till","Loess","Alluvium","Varve"],answer:0,explain:"Till is deposited directly by ice (poorly sorted). Outwash is sorted meltwater sediment; loess is wind-blown silt.",source:"original",productSafe:true},
  {id:30,domain:"geomorph",topic:"Fluvial",difficulty:"medium",q:"Braided streams (vs meandering) typically form where there is:",choices:["Low gradient and fine suspended load","High, variable sediment load and discharge","No sediment supply","Tidal influence only"],answer:1,explain:"Braided channels form with abundant coarse bedload and variable discharge; meandering channels favor lower gradients and suspended load.",source:"original",productSafe:true},
  {id:31,domain:"geomorph",topic:"Eolian",difficulty:"easy",q:"Loess is a deposit of:",choices:["Wind-blown silt","River gravel","Volcanic ash flows","Beach sand"],answer:0,explain:"Loess is wind-transported silt, often blanketing regions downwind of glacial outwash.",source:"original",productSafe:true},
  {id:32,domain:"geomorph",topic:"Karst",difficulty:"medium",q:"Karst topography (sinkholes, caves) develops mainly by:",choices:["Dissolution of soluble rock like limestone","Glacial plucking","Wind abrasion","Lava flows"],answer:0,explain:"Slightly acidic groundwater dissolves carbonate (and evaporite) rock, creating caves and sinkholes.",source:"original",productSafe:true},
  {id:33,domain:"geomorph",topic:"Soils",difficulty:"medium",q:"In a typical soil profile, the organic-rich surface layer is the:",choices:["O horizon","B horizon","C horizon","R horizon"],answer:0,explain:"O = organic surface; A = topsoil; B = zone of accumulation; C = weathered parent material; R = bedrock.",source:"original",productSafe:true},
  {id:34,domain:"geomorph",topic:"Mass wasting",difficulty:"medium",q:"The slow, gradual downslope movement of soil under gravity is called:",choices:["Rockfall","Creep","Liquefaction","Saltation"],answer:1,explain:"Creep is imperceptibly slow downslope soil movement (tilted poles/fences are evidence). Rockfall is rapid free-fall of rock.",source:"original",productSafe:true},

  // ===== STRUCTURE, TECTONICS & SEISMOLOGY =====
  {id:35,domain:"structure",topic:"Faults",difficulty:"medium",q:"In a normal fault, the hanging wall moves ___ under ___ stress.",choices:["up; compression","down; extension","laterally; shear","none; lithostatic"],answer:1,explain:"Normal faults drop the hanging wall under extension; reverse/thrust faults raise it under compression.",source:"original",productSafe:true},
  {id:36,domain:"structure",topic:"Folds",difficulty:"medium",q:"In an eroded anticline, the oldest rocks are exposed:",choices:["In the core (center)","On the outer limbs","At the surface edges","Randomly"],answer:0,explain:"Anticlines arch up, exposing oldest beds in the core; synclines have youngest rocks in the core.",source:"original",productSafe:true},
  {id:37,domain:"structure",topic:"Plate boundaries",difficulty:"easy",q:"Mid-ocean ridges and seafloor spreading occur at which boundary?",choices:["Convergent","Divergent","Transform","Passive margin"],answer:1,explain:"Divergent boundaries create new oceanic crust at ridges.",source:"original",productSafe:true},
  {id:38,domain:"structure",topic:"Plate boundaries",difficulty:"medium",q:"Deep trenches, inclined deep-earthquake zones, and volcanic arcs characterize:",choices:["Divergent boundaries","Convergent (subduction) boundaries","Transform boundaries","Hotspots"],answer:1,explain:"A subducting slab creates the trench, the Wadati-Benioff seismic zone, and arc volcanism.",source:"original",productSafe:true},
  {id:39,domain:"structure",topic:"Seismology",difficulty:"hard",q:"Which statement about seismic body waves is CORRECT?",choices:["S-waves are faster than P-waves","P-waves cannot pass through liquids","S-waves cannot travel through the liquid outer core","Both travel only through solids"],answer:2,explain:"P-waves (fastest, compressional) pass through solids and liquids; S-waves (shear) cannot pass through liquids.",source:"original",productSafe:true},
  {id:40,domain:"structure",topic:"Seismology",difficulty:"medium",q:"To locate an earthquake's epicenter, you minimally need data from:",choices:["One seismograph","Two seismographs","Three or more seismographs (triangulation)","No seismographs"],answer:2,explain:"S–P arrival times give distance to each station; three+ distance circles triangulate the epicenter.",source:"original",productSafe:true},

  // ===== HYDROGEOLOGY =====
  {id:41,domain:"hydro",topic:"Properties",difficulty:"medium",q:"Permeability differs from porosity in that permeability measures:",choices:["Total void fraction","The ability to transmit fluid","Mineral hardness","Grain diameter"],answer:1,explain:"Porosity = void fraction; permeability = how well voids interconnect to transmit fluid. Clay is porous but nearly impermeable.",source:"original",productSafe:true},
  {id:42,domain:"hydro",topic:"Darcy's law",difficulty:"hard",q:"In Darcy's law (Q = K·i·A), the term 'i' represents the:",choices:["Hydraulic gradient (head change per distance)","Porosity","Pumping rate","Pipe diameter"],answer:0,explain:"Q = K i A: K = hydraulic conductivity, i = hydraulic gradient (dh/dl), A = cross-sectional area. Flow increases with gradient and conductivity.",source:"original",productSafe:true},
  {id:43,domain:"hydro",topic:"Aquifers",difficulty:"medium",q:"A low-permeability layer that retards groundwater flow is an:",choices:["Aquifer","Aquitard/aquiclude","Artesian well","Aquihole"],answer:1,explain:"An aquitard (or aquiclude) restricts flow; an aquifer readily stores and transmits water.",source:"original",productSafe:true},
  {id:44,domain:"hydro",topic:"Aquifers",difficulty:"medium",q:"Water in a confined aquifer under enough pressure to rise above the aquifer top in a well is:",choices:["Perched water","Artesian (confined) conditions","An unconfined aquifer","A vadose zone"],answer:1,explain:"Confined aquifers between aquitards can be pressurized; the potentiometric surface lies above the aquifer top (artesian).",source:"original",productSafe:true},
  {id:45,domain:"hydro",topic:"Wells",difficulty:"medium",q:"Pumping a well lowers the water table around it into a feature called the:",choices:["Cone of depression","Capillary fringe","Recharge mound","Perched lens"],answer:0,explain:"Drawdown creates a cone of depression centered on the pumping well; overlapping cones cause well interference.",source:"original",productSafe:true},
  {id:46,domain:"hydro",topic:"Water table",difficulty:"easy",q:"The water table is best defined as:",choices:["The top of the zone of saturation","The bottom of all groundwater","The ground surface","An impermeable layer"],answer:0,explain:"It is the surface separating the unsaturated (vadose) zone above from the saturated zone below.",source:"original",productSafe:true},
  {id:47,domain:"hydro",topic:"Contaminant transport",difficulty:"hard",q:"A dissolved contaminant plume in groundwater generally migrates:",choices:["Upward against gravity","Down the hydraulic gradient (toward lower head)","Only sideways at random","It never moves"],answer:1,explain:"Advection carries dissolved contaminants in the direction of groundwater flow, i.e., down the hydraulic gradient, with dispersion spreading the plume.",source:"original",productSafe:true},
  {id:48,domain:"hydro",topic:"Storage",difficulty:"hard",q:"Specific yield is the portion of water that a saturated material will:",choices:["Release by gravity drainage","Retain by surface tension","Convert to vapor","Freeze"],answer:0,explain:"Specific yield = drainable water; specific retention = water held against gravity. Porosity ≈ specific yield + specific retention.",source:"original",productSafe:true},
  {id:49,domain:"hydro",topic:"Properties",difficulty:"medium",q:"Which earth material typically has HIGH porosity but LOW permeability?",choices:["Clean gravel","Fractured basalt","Clay","Well-sorted sand"],answer:2,explain:"Clay has lots of tiny pores (high porosity) but the pores are poorly connected and hold water tightly, giving very low permeability.",source:"original",productSafe:true},
  {id:50,domain:"hydro",topic:"Quantities",difficulty:"hard",q:"Transmissivity equals hydraulic conductivity multiplied by:",choices:["The saturated aquifer thickness","The porosity","The pumping time","The well radius"],answer:0,explain:"T = K·b, where b is the saturated thickness; it describes how much water an aquifer's full thickness can transmit.",source:"original",productSafe:true},

  // ===== ENGINEERING GEOLOGY =====
  {id:51,domain:"engineering",topic:"Soil mechanics",difficulty:"hard",q:"Terzaghi's effective stress (σ′) equals total stress (σ) minus:",choices:["Pore-water pressure (u)","Cohesion","The friction angle","Overburden"],answer:0,explain:"σ′ = σ − u. Rising pore pressure lowers effective stress and shear strength, a key idea in slope and foundation failure.",source:"original",productSafe:true},
  {id:52,domain:"engineering",topic:"Geohazards",difficulty:"medium",q:"Liquefaction during an earthquake is most likely in:",choices:["Dry bedrock","Loose, saturated sand/silt","Dense gravel above the water table","Solid granite"],answer:1,explain:"Shaking raises pore pressure in loose, saturated granular soils until they lose strength and behave like a fluid.",source:"original",productSafe:true},
  {id:53,domain:"engineering",topic:"Soil index",difficulty:"hard",q:"Atterberg limits (liquid limit, plastic limit) are used to characterize:",choices:["The consistency/plasticity behavior of fine-grained soils","Rock hardness","Permeability of gravel","Seismic velocity"],answer:0,explain:"They mark water contents where a fine soil changes behavior; plasticity index = LL − PL, used in soil classification.",source:"original",productSafe:true},
  {id:54,domain:"engineering",topic:"Expansive soils",difficulty:"medium",q:"Which clay mineral causes the most damaging shrink-swell (expansive) behavior?",choices:["Kaolinite","Smectite (montmorillonite)","Quartz","Gypsum"],answer:1,explain:"Smectite/montmorillonite absorbs water between layers and swells, cracking foundations and pavements.",source:"original",productSafe:true},
  {id:55,domain:"engineering",topic:"Slope stability",difficulty:"medium",q:"A slope's factor of safety is the ratio of:",choices:["Resisting forces to driving forces","Cost to benefit","Rainfall to runoff","Porosity to permeability"],answer:0,explain:"FS = resisting/driving forces; FS < 1 means failure. Adding water (driving forces up, strength down) lowers FS.",source:"original",productSafe:true},
  {id:56,domain:"engineering",topic:"Rock mass",difficulty:"hard",q:"Rock Quality Designation (RQD) is computed from drill core as:",choices:["The % of core in intact pieces ≥ 10 cm long","The core diameter","The drilling speed","The number of minerals present"],answer:0,explain:"RQD = (sum of core pieces ≥10 cm / total core run) × 100; higher RQD = more competent, less fractured rock.",source:"original",productSafe:true},
  {id:57,domain:"engineering",topic:"Foundations",difficulty:"medium",q:"The maximum slope angle a loose granular pile can maintain is its:",choices:["Angle of repose","Dip angle","Liquid limit","Hydraulic gradient"],answer:0,explain:"The angle of repose is the steepest stable angle for loose, dry granular material.",source:"original",productSafe:true},
  {id:58,domain:"engineering",topic:"Mass wasting",difficulty:"medium",q:"A slump is a mass movement that:",choices:["Falls freely through air","Rotates downward along a curved (concave) failure surface","Flows as a saturated slurry","Creeps over centuries"],answer:1,explain:"Slumps move as coherent blocks rotating along a curved (spoon-shaped) slip surface, often leaving a back-tilted scarp.",source:"original",productSafe:true},

  // ===== ECONOMIC GEOLOGY & ENERGY =====
  {id:59,domain:"economic",topic:"Petroleum",difficulty:"hard",q:"A complete petroleum system minimally requires a source rock, a migration path, a trap, and:",choices:["A porous/permeable reservoir plus an impermeable seal","A coal seam","A fault only","A volcanic vent"],answer:0,explain:"Hydrocarbons form in an organic source rock, migrate into a porous-permeable reservoir, and are held by a seal/cap rock within a structural or stratigraphic trap.",source:"original",productSafe:true},
  {id:60,domain:"economic",topic:"Coal",difficulty:"medium",q:"Which lists coal in order of INCREASING rank (carbon content/maturity)?",choices:["Anthracite → bituminous → lignite → peat","Peat → lignite → bituminous → anthracite","Lignite → peat → anthracite → bituminous","Bituminous → peat → lignite → anthracite"],answer:1,explain:"Increasing burial/heat: peat → lignite → sub-bituminous → bituminous → anthracite (highest rank, most carbon).",source:"original",productSafe:true},
  {id:61,domain:"economic",topic:"Ore deposits",difficulty:"hard",q:"Porphyry copper deposits are:",choices:["High-grade veins in limestone","Large, low-grade disseminated deposits linked to intermediate-felsic intrusions","Placer concentrations in rivers","Evaporite beds"],answer:1,explain:"Porphyry deposits are large-tonnage, low-grade disseminated sulfides associated with shallow intrusions; they supply most of the world's copper.",source:"original",productSafe:true},
  {id:62,domain:"economic",topic:"Ore deposits",difficulty:"medium",q:"Placer gold deposits form by:",choices:["Mechanical concentration of dense grains in flowing water","Volcanic eruption","Metamorphism of shale","Evaporation of seawater"],answer:0,explain:"Heavy, resistant minerals (gold, magnetite) settle out where current slows, concentrating in stream gravels (placers).",source:"original",productSafe:true},
  {id:63,domain:"economic",topic:"Resources",difficulty:"medium",q:"The key difference between a 'reserve' and a 'resource' is that a reserve is:",choices:["Always larger","The portion that is economically and legally extractable now","Purely hypothetical","Only offshore"],answer:1,explain:"Resources include all identified plus undiscovered material; reserves are the subset that is currently economic and legal to extract.",source:"original",productSafe:true},
];
